{inputs, ...}: {
  perSystem = {
    pkgs,
    system,
    ...
  }: {
    checks.installer-dry-run = pkgs.testers.nixosTest {
      name = "installer-dry-run";

      nodes.machine = {pkgs, ...}: {
        environment.systemPackages = with pkgs; [
          nixos-install-tools # provides nixos-generate-config
          openssh
          sbctl
          ssh-to-age
          util-linux # lsblk
        ];
        virtualisation.memorySize = 1024;
        virtualisation.useEFIBoot = true; # required for sbctl EFI variable access
      };

      testScript = let
        installer = pkgs.writeShellApplication {
          name = "snros-install-test";
          runtimeInputs = with pkgs; [
            git
            inputs.disko.packages.${system}.disko
            openssh
            sbctl
            ssh-to-age
          ];
          text = builtins.readFile ../scripts/install.sh;
        };
      in ''
        host = "dell-xps-9500"
        clone_dir = "/tmp/snros-test"
        # Nix interpolation: ${installer} is replaced with the store path at eval time
        installer_bin = "${installer}/bin/snros-install-test"

        machine.wait_for_unit("multi-user.target")

        # Pre-populate CLONE_DIR — SNROS_CLONE_DIR being set tells the installer to skip git clone
        machine.succeed(f"mkdir -p {clone_dir}/modules/hosts/{host}/etc/ssh")
        machine.succeed(f"mkdir -p {clone_dir}/devices/{host}")

        # Pre-seed the SSH host key so the installer proceeds past the key-generation early-exit
        machine.succeed(
          f"ssh-keygen -t ed25519"
          f" -f {clone_dir}/modules/hosts/{host}/etc/ssh/ssh_host_ed25519_key"
          f" -N \"\" -C {host}"
        )
        machine.succeed(
          f"chmod 600"
          f" {clone_dir}/modules/hosts/{host}/etc/ssh/ssh_host_ed25519_key"
        )

        # Run the installer in dry-run mode; SNROS_CLONE_DIR skips git clone and host validation
        machine.succeed(
          f"SNROS_CLONE_DIR={clone_dir}"
          f" {installer_bin} --dry-run {host} 2>&1 | tee /tmp/installer.log"
        )

        # Assert: hardware config was generated by nixos-generate-config
        machine.succeed(f"test -f {clone_dir}/devices/{host}/hardware-configuration.nix")

        # Assert: secureboot keys were generated by sbctl
        machine.succeed(f"test -d {clone_dir}/modules/hosts/{host}/persist/secureboot/keys")

        # Assert: dry-run completed successfully (not a real install)
        machine.succeed("grep -q 'Dry run complete' /tmp/installer.log")
      '';
    };
  };
}
