# Wraps a hardware-configuration.nix generated by nixos-generate-config as a
# NixOS module. Only boot, hardware, and nixpkgs settings are exposed.
# fileSystems, swapDevices, and installer imports are discarded — disk layout
# is managed by disko.
path: {
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  hw = import path {inherit config lib pkgs modulesPath;};
in {
  inherit (hw) boot nixpkgs;
  hardware = hw.hardware or {};
}
