# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/iso" = {
    device = "/dev/disk/by-uuid/1980-01-01-00-00-00-00";
    fsType = "iso9660";
  };

  fileSystems."/nix/.ro-store" = {
    device = "/iso/nix-store.squashfs";
    fsType = "squashfs";
    options = ["loop"];
  };

  fileSystems."/nix/.rw-store" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  fileSystems."/nix/store" = {
    device = "overlay";
    fsType = "overlay";
  };

  fileSystems."/mnt" = {
    device = "rpool/local/root";
    fsType = "zfs";
  };

  fileSystems."/mnt/boot" = {
    device = "/dev/disk/by-uuid/2849-1155";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/home" = {
    device = "rpool/safe/home";
    fsType = "zfs";
  };

  fileSystems."/mnt/nix" = {
    device = "rpool/local/nix";
    fsType = "zfs";
  };

  fileSystems."/mnt/persist" = {
    device = "rpool/safe/persist";
    fsType = "zfs";
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
